version: '3.8'
services:
  app:
    environment:
      PHP_OPCACHE_ENABLE: 0
      PHP_XDEBUG_ENABLE: 0
      PHP_IDE_CONFIG: "serverName=local"
      AUTOSTART_COMPOSER: "0"
      AUTOSTART_MIGRATIONS: "0"
      AUTOSTART_QUEUE: "0"
      AUTOSTART_SEED_PERMISSIONS: "0"
      AUTOSTART_WEBSOCKETS: "1"
    ports:
      - '32400:80/tcp'

  adminer:
    image: adminer
    ports:
      - '32401:8080/tcp'

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '32402:8025/tcp'
