version: '3.8'
services:
  db:
    image: mariadb:10.7.3
    environment:
      MYSQL_ROOT_PASSWORD: dev123
      MYSQL_DATABASE: hito

  redis:
    image: redis:6.2.7

  app:
    image: ghcr.io/hito-software/hito:develop
    pull_policy: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env
    environment:
      PHP_OPCACHE_ENABLE: 0
      PHP_XDEBUG_ENABLE: 0
      PHP_XDEBUG_START_WITH_REQUEST: "trigger"
      PHP_XDEBUG_MODE: "develop,debug"
